name: AppWright Test
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Start job server
        run: |
          uvicorn server.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Submit test job
        id: submit
        run: |
          output=$(qgjob submit --org-id=qualgent --app-version-id=xyz123 --test=tests/onboarding.spec.js)
          echo "::set-output name=jobid::$(echo $output | awk '{print $3}')"

      - name: Poll for completion
        run: |
          JOB_ID=${{ steps.submit.outputs.jobid }}
          status=""
          until [ "$status" = "completed" ]; do
            echo "Checking status for $JOB_ID..."
            sleep 5
            status=$(qgjob status --job-id=$JOB_ID | awk '{print $3}')
            if [ "$status" = "failed" ]; then
              echo "Job $JOB_ID failed."
              exit 1
            fi
          done
          echo "Job $JOB_ID completed successfully."
